POST http://localhost:3001/product
Content-Type: application/json

{
        "name": "asd",
        "price": 189.99,
        "details": 
        [
          {
                "brand": "SilverStone Technology"
          }
        ],
        "category": "cases",
        "discount": "asd",
        "quantity": "1"
}